import PoetItem from "./PoetItem";

const PoetsList = () => {
  const dummyPoets = [
    {
      id: 57,
      name: "ابن حسام خوسفی",
      description: null,
      fullUrl: "/ebnehesam",
      rootCatId: 1870,
      nickname: "ابن حسام خوسفی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/ebnehesam.gif",
      birthYearInLHijri: 782,
      validBirthDate: true,
      deathYearInLHijri: 875,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "خوسف",
      birthPlaceLatitude: 32.7811,
      birthPlaceLongitude: 58.892,
      deathPlace: "خوسف",
      deathPlaceLatitude: 32.7811,
      deathPlaceLongitude: 58.892,
    },
    {
      id: 106,
      name: "ابن یمین فریومدی",
      description: null,
      fullUrl: "/ebneyamin",
      rootCatId: 2424,
      nickname: "ابن یمین",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/ebneyamin.gif",
      birthYearInLHijri: 685,
      validBirthDate: true,
      deathYearInLHijri: 769,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "فریومد",
      birthPlaceLatitude: 36.5151,
      birthPlaceLongitude: 56.7496,
      deathPlace: "فریومد",
      deathPlaceLatitude: 36.5151,
      deathPlaceLongitude: 56.7496,
    },
    {
      id: 114,
      name: "ابوالحسن فراهانی",
      description: null,
      fullUrl: "/abolhasan",
      rootCatId: 2472,
      nickname: "ابوالحسن فراهانی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/abolhasan.gif",
      birthYearInLHijri: 1001,
      validBirthDate: false,
      deathYearInLHijri: 1040,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "",
      birthPlaceLatitude: 0,
      birthPlaceLongitude: 0,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 110,
      name: "ابوالفرج رونی",
      description: null,
      fullUrl: "/rooni",
      rootCatId: 2452,
      nickname: "ابوالفرج رونی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/rooni.gif",
      birthYearInLHijri: 450,
      validBirthDate: false,
      deathYearInLHijri: 525,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "نیشابور",
      birthPlaceLatitude: 36.2141,
      birthPlaceLongitude: 58.7961,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 26,
      name: "ابوسعید ابوالخیر",
      description: null,
      fullUrl: "/abusaeed",
      rootCatId: 304,
      nickname: "ابوسعید ابوالخیر",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/abusaeed.gif",
      birthYearInLHijri: 357,
      validBirthDate: true,
      deathYearInLHijri: 440,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "میهنه",
      birthPlaceLatitude: 36.871667,
      birthPlaceLongitude: 60.404167,
      deathPlace: "میهنه",
      deathPlaceLatitude: 36.871667,
      deathPlaceLongitude: 60.404167,
    },
    {
      id: 101,
      name: "ابوعلی حسن بن احمد عثمانی",
      description: null,
      fullUrl: "/osmani",
      rootCatId: 2388,
      nickname: "ابوعلی عثمانی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/osmani.gif",
      birthYearInLHijri: 401,
      validBirthDate: false,
      deathYearInLHijri: 485,
      validDeathDate: false,
      pinOrder: 0,
      birthPlace: "نیشابور",
      birthPlaceLatitude: 36.2141,
      birthPlaceLongitude: 58.7961,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 143,
      name: "اثیر اخسیکتی",
      description: null,
      fullUrl: "/akhsikati",
      rootCatId: 2686,
      nickname: "اثیر اخسیکتی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/akhsikati.gif",
      birthYearInLHijri: 560,
      validBirthDate: false,
      deathYearInLHijri: 609,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "اخسیکت",
      birthPlaceLatitude: 40.886569,
      birthPlaceLongitude: 71.450602,
      deathPlace: "خلخال",
      deathPlaceLatitude: 48.525278,
      deathPlaceLongitude: 37.616111,
    },
    {
      id: 147,
      name: "ادیب الممالک فراهانی",
      description: null,
      fullUrl: "/adib",
      rootCatId: 2718,
      nickname: "ادیب الممالک",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/adib.gif",
      birthYearInLHijri: 1277,
      validBirthDate: true,
      deathYearInLHijri: 1336,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "گازران",
      birthPlaceLatitude: 34.575,
      birthPlaceLongitude: 49.617778,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 156,
      name: "ادیب صابر",
      description: null,
      fullUrl: "/saber",
      rootCatId: 2816,
      nickname: "ادیب صابر",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/saber.gif",
      birthYearInLHijri: 505,
      validBirthDate: false,
      deathYearInLHijri: 546,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "ترمذ",
      birthPlaceLatitude: 37.216667,
      birthPlaceLongitude: 67.283333,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 63,
      name: "ازرقی هروی",
      description: null,
      fullUrl: "/azraghi",
      rootCatId: 2034,
      nickname: "ازرقی هروی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/azraghi.gif",
      birthYearInLHijri: 400,
      validBirthDate: false,
      deathYearInLHijri: 465,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "هرات",
      birthPlaceLatitude: 34.3529,
      birthPlaceLongitude: 62.204,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 114,
      name: "ابوالحسن فراهانی",
      description: null,
      fullUrl: "/abolhasan",
      rootCatId: 2472,
      nickname: "ابوالحسن فراهانی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/abolhasan.gif",
      birthYearInLHijri: 1001,
      validBirthDate: false,
      deathYearInLHijri: 1040,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "",
      birthPlaceLatitude: 0,
      birthPlaceLongitude: 0,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 110,
      name: "ابوالفرج رونی",
      description: null,
      fullUrl: "/rooni",
      rootCatId: 2452,
      nickname: "ابوالفرج رونی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/rooni.gif",
      birthYearInLHijri: 450,
      validBirthDate: false,
      deathYearInLHijri: 525,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "نیشابور",
      birthPlaceLatitude: 36.2141,
      birthPlaceLongitude: 58.7961,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 26,
      name: "ابوسعید ابوالخیر",
      description: null,
      fullUrl: "/abusaeed",
      rootCatId: 304,
      nickname: "ابوسعید ابوالخیر",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/abusaeed.gif",
      birthYearInLHijri: 357,
      validBirthDate: true,
      deathYearInLHijri: 440,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "میهنه",
      birthPlaceLatitude: 36.871667,
      birthPlaceLongitude: 60.404167,
      deathPlace: "میهنه",
      deathPlaceLatitude: 36.871667,
      deathPlaceLongitude: 60.404167,
    },
    {
      id: 101,
      name: "ابوعلی حسن بن احمد عثمانی",
      description: null,
      fullUrl: "/osmani",
      rootCatId: 2388,
      nickname: "ابوعلی عثمانی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/osmani.gif",
      birthYearInLHijri: 401,
      validBirthDate: false,
      deathYearInLHijri: 485,
      validDeathDate: false,
      pinOrder: 0,
      birthPlace: "نیشابور",
      birthPlaceLatitude: 36.2141,
      birthPlaceLongitude: 58.7961,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 143,
      name: "اثیر اخسیکتی",
      description: null,
      fullUrl: "/akhsikati",
      rootCatId: 2686,
      nickname: "اثیر اخسیکتی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/akhsikati.gif",
      birthYearInLHijri: 560,
      validBirthDate: false,
      deathYearInLHijri: 609,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "اخسیکت",
      birthPlaceLatitude: 40.886569,
      birthPlaceLongitude: 71.450602,
      deathPlace: "خلخال",
      deathPlaceLatitude: 48.525278,
      deathPlaceLongitude: 37.616111,
    },
    {
      id: 147,
      name: "ادیب الممالک فراهانی",
      description: null,
      fullUrl: "/adib",
      rootCatId: 2718,
      nickname: "ادیب الممالک",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/adib.gif",
      birthYearInLHijri: 1277,
      validBirthDate: true,
      deathYearInLHijri: 1336,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "گازران",
      birthPlaceLatitude: 34.575,
      birthPlaceLongitude: 49.617778,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 156,
      name: "ادیب صابر",
      description: null,
      fullUrl: "/saber",
      rootCatId: 2816,
      nickname: "ادیب صابر",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/saber.gif",
      birthYearInLHijri: 505,
      validBirthDate: false,
      deathYearInLHijri: 546,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "ترمذ",
      birthPlaceLatitude: 37.216667,
      birthPlaceLongitude: 67.283333,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 63,
      name: "ازرقی هروی",
      description: null,
      fullUrl: "/azraghi",
      rootCatId: 2034,
      nickname: "ازرقی هروی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/azraghi.gif",
      birthYearInLHijri: 400,
      validBirthDate: false,
      deathYearInLHijri: 465,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "هرات",
      birthPlaceLatitude: 34.3529,
      birthPlaceLongitude: 62.204,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 114,
      name: "ابوالحسن فراهانی",
      description: null,
      fullUrl: "/abolhasan",
      rootCatId: 2472,
      nickname: "ابوالحسن فراهانی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/abolhasan.gif",
      birthYearInLHijri: 1001,
      validBirthDate: false,
      deathYearInLHijri: 1040,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "",
      birthPlaceLatitude: 0,
      birthPlaceLongitude: 0,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 110,
      name: "ابوالفرج رونی",
      description: null,
      fullUrl: "/rooni",
      rootCatId: 2452,
      nickname: "ابوالفرج رونی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/rooni.gif",
      birthYearInLHijri: 450,
      validBirthDate: false,
      deathYearInLHijri: 525,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "نیشابور",
      birthPlaceLatitude: 36.2141,
      birthPlaceLongitude: 58.7961,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 26,
      name: "ابوسعید ابوالخیر",
      description: null,
      fullUrl: "/abusaeed",
      rootCatId: 304,
      nickname: "ابوسعید ابوالخیر",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/abusaeed.gif",
      birthYearInLHijri: 357,
      validBirthDate: true,
      deathYearInLHijri: 440,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "میهنه",
      birthPlaceLatitude: 36.871667,
      birthPlaceLongitude: 60.404167,
      deathPlace: "میهنه",
      deathPlaceLatitude: 36.871667,
      deathPlaceLongitude: 60.404167,
    },
    {
      id: 101,
      name: "ابوعلی حسن بن احمد عثمانی",
      description: null,
      fullUrl: "/osmani",
      rootCatId: 2388,
      nickname: "ابوعلی عثمانی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/osmani.gif",
      birthYearInLHijri: 401,
      validBirthDate: false,
      deathYearInLHijri: 485,
      validDeathDate: false,
      pinOrder: 0,
      birthPlace: "نیشابور",
      birthPlaceLatitude: 36.2141,
      birthPlaceLongitude: 58.7961,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 143,
      name: "اثیر اخسیکتی",
      description: null,
      fullUrl: "/akhsikati",
      rootCatId: 2686,
      nickname: "اثیر اخسیکتی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/akhsikati.gif",
      birthYearInLHijri: 560,
      validBirthDate: false,
      deathYearInLHijri: 609,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "اخسیکت",
      birthPlaceLatitude: 40.886569,
      birthPlaceLongitude: 71.450602,
      deathPlace: "خلخال",
      deathPlaceLatitude: 48.525278,
      deathPlaceLongitude: 37.616111,
    },
    {
      id: 147,
      name: "ادیب الممالک فراهانی",
      description: null,
      fullUrl: "/adib",
      rootCatId: 2718,
      nickname: "ادیب الممالک",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/adib.gif",
      birthYearInLHijri: 1277,
      validBirthDate: true,
      deathYearInLHijri: 1336,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "گازران",
      birthPlaceLatitude: 34.575,
      birthPlaceLongitude: 49.617778,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 156,
      name: "ادیب صابر",
      description: null,
      fullUrl: "/saber",
      rootCatId: 2816,
      nickname: "ادیب صابر",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/saber.gif",
      birthYearInLHijri: 505,
      validBirthDate: false,
      deathYearInLHijri: 546,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "ترمذ",
      birthPlaceLatitude: 37.216667,
      birthPlaceLongitude: 67.283333,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
    {
      id: 63,
      name: "ازرقی هروی",
      description: null,
      fullUrl: "/azraghi",
      rootCatId: 2034,
      nickname: "ازرقی هروی",
      published: true,
      imageUrl: "/api/ganjoor/poet/image/azraghi.gif",
      birthYearInLHijri: 400,
      validBirthDate: false,
      deathYearInLHijri: 465,
      validDeathDate: true,
      pinOrder: 0,
      birthPlace: "هرات",
      birthPlaceLatitude: 34.3529,
      birthPlaceLongitude: 62.204,
      deathPlace: "",
      deathPlaceLatitude: 0,
      deathPlaceLongitude: 0,
    },
  ];

  return (
    <section className="py-5">
      <div className="container px-4 mx-auto">
        <div className="flex flex-wrap justify-center">
          {dummyPoets.map((item) => (
            <PoetItem key={item.name} item={item} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default PoetsList;
